os: linux
dist: bionic

language: ruby
cache: bundler
gemfile: server/Gemfile
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '9.5'
script:
  - cd server
  - bin/rails db:environment:set RAILS_ENV=test
  - bin/bundle exec rspec spec 
