version: '3'

services:
  server:
    container_name: server 
    build: ./server
    image: customserver
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=I3M5GDF8!
      - POSTGRES_USER=mentoruser
      - POSTGRES_DB=mentormentee
    ports:
      - '3000:3000'
    volumes:
      - ./server/:/usr/src/app
  
  # based on https://mherman.org/blog/dockerizing-a-react-app/
  my-app:
    container_name: my-app
    build: ./my-app
    image: customweb
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '80:3000'
    volumes:
      - ./my-app:/app
      - '/app/node_modules'
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=mentormentee
      - POSTGRES_PASSWORD=I3M5GDF8!
      - POSTGRES_USER=mentoruser
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data:
