version: '3'

services:
  server:
    container_name: server 
    build: ./server
    image: customserver
    ports:
      - '3000:3000'
    volumes:
      - ./server/:/usr/src/app
  my-app:
    container_name: my-app
    build: ./my-app
    image: customweb
    environment:
      - CI=true
    ports:
      - '80:3000'
    volumes:
      - ./my-app:/app
  postgres:
    container_name: pg_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data:
#docker-compose run server /bin/bash
#docker-compose run web /bin/sh
#or use exec eg.
#docker container exec pg_db bash
#then you type psql -U myuser
#then get \l to get databases
