version: "3"

services:
  server:
    container_name: server
    build: ./server
    image: railsgirlscph/mentormenteeplatform-server:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mentormentee
      - POSTGRES_PASSWORD=${MY_SECRET_KEY}
      - POSTGRES_USER=mentoruser

    ports:
      - "3000:3000"
    volumes:
      - ./server/:/app
    tmpfs:
      - /app/tmp
  ui:
    container_name: ui
    build: ./my-app
    image: railsgirlscph/mentormenteeplatform-ui
    environment:
      - CI=true
    ports:
      - "80:3000"
    volumes:
      - ./my-app/:/app
    tmpfs:
      - /app/tmp
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=mentormentee
      - POSTGRES_PASSWORD=${MY_SECRET_KEY}
      - POSTGRES_USER=mentoruser
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data:
